# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# goreleaser version 1.16.0
#commit: 945b5453d953e36c7fcad8ff64206c021413271b
# built by: homebrew
# goos: darwin
# goarch: arm64

# .goreleaser.yml
project_name: integrationcli

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: integrationcli
    main: ./main.go
    binary: integrationcli
    goos:
      - linux
      - darwin
      - windows
    flags:
    - -trimpath
    ldflags:
    - -s -w -a -extldflags "-static" -X main.Version={{.Tag}} -X main.Git={{.Commit}}
    gcflags:
    - all="-l"
    env:
      - CGO_ENABLED=0

archives:
  - id: integrationcli
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "windows" }}Windows
      {{- else if eq .Arch "darwin" }}Darwin
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    builds:
      - integrationcli

checksum:
  name_template: 'checksums.txt'

signs:
  -
    artifacts: all
    args:
      [
        "-u",
        "13950006+srinandan@users.noreply.github.com",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

release:
  draft: true
  prerelease: true
