# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# gcloud builds submit --config=artifact-build.yaml --project=project-name --substitutions=TAG="v0.65"
steps:
#publish integrationcli
- name: 'gcr.io/cloud-builders/docker'
  id: build_integrationcli
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_NAME}:${TAG_NAME}'
    - '-f'
    - 'Dockerfile'
    - '.'
    - '--build-arg'
    - 'TAG=${TAG_NAME}'
    - '--build-arg'
    - 'COMMIT=$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  id: push_integrationcli
  args: ['push', '${_IMAGE_NAME}:${TAG_NAME}']
- name: 'gcr.io/cloud-builders/docker'
  id: tag_latest_integrationcli
  args: ['tag', '${_IMAGE_NAME}:${TAG_NAME}', '${_IMAGE_NAME}:latest']
- name: 'gcr.io/cloud-builders/docker'
  id: push_latest_integrationcli
  args: ['push', '${_IMAGE_NAME}:latest']
#publish integrationcli-builder
- name: 'gcr.io/cloud-builders/docker'
  id: build_integrationcli_builder
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_NAME}-builder:${TAG_NAME}'
    - '-f'
    - 'Dockerfile.builder'
    - '.'
    - '--build-arg'
    - 'TAG=${TAG_NAME}'
    - '--build-arg'
    - 'COMMIT=$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}-builder:${TAG_NAME}']
- name: 'gcr.io/cloud-builders/docker'
  id: tag_latest_integrationcli_builder
  args: ['tag', '${_IMAGE_NAME}-builder:${TAG_NAME}', '${_IMAGE_NAME}-builder:latest']
- name: 'gcr.io/cloud-builders/docker'
  id: push_latest_integrationcli_builder
  args: ['push', '${_IMAGE_NAME}-builder:latest']

#sign and attach integrationcli
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: sign_integrationcli
  entrypoint: 'sh'
  env:
    - 'COSIGN_PASSWORD=${_COSIGN_PASSWORD}'
  args:
    - '-c'
    - 'echo "${_COSIGN_PRIVATE_KEY}" > /tmp/cosign.key && cosign sign --key=/tmp/cosign.key --output-signature=/tmp/integrationcli_${TAG_NAME}.sig --yes ${_IMAGE_NAME}:${TAG_NAME}'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: attach_sign_integrationcli
  entrypoint: 'sh'
  args:
    - '-c'
    - 'cosign attach signature --signature=/tmp/integrationcli_${TAG_NAME}.sig ${_IMAGE_NAME}:${TAG_NAME}'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: sign_latest_integrationcli
  entrypoint: 'sh'
  env:
    - 'COSIGN_PASSWORD=${_COSIGN_PASSWORD}'
  args:
    - '-c'
    - 'echo "${_COSIGN_PRIVATE_KEY}" > /tmp/cosign.key && cosign sign --key=/tmp/cosign.key --output-signature=/tmp/integrationcli_latest.sig --yes ${_IMAGE_NAME}:latest'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: attach_latest_sign_integrationcli
  entrypoint: 'sh'
  args:
    - '-c'
    - 'cosign attach signature --signature=/tmp/integrationcli_latest.sig ${_IMAGE_NAME}:latest'
#sign and attach integrationcli-builder
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: sign_integrationcli_builder
  entrypoint: 'sh'
  env:
    - 'COSIGN_PASSWORD=${_COSIGN_PASSWORD}'
  args:
    - '-c'
    - 'echo "${_COSIGN_PRIVATE_KEY}" > /tmp/cosign.key && cosign sign --key=/tmp/cosign.key --output-signature=/tmp/integrationcli-builder_${TAG_NAME}.sig --yes ${_IMAGE_NAME}-builder:${TAG_NAME}'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: attach_sign_integrationcli_builder
  entrypoint: 'sh'
  args:
    - '-c'
    - 'cosign attach signature --signature=/tmp/integrationcli-builder_${TAG_NAME}.sig ${_IMAGE_NAME}-builder:${TAG_NAME}'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: sign_latest_integrationcli_builder
  entrypoint: 'sh'
  env:
    - 'COSIGN_PASSWORD=${_COSIGN_PASSWORD}'
  args:
    - '-c'
    - 'echo "${_COSIGN_PRIVATE_KEY}" > /tmp/cosign.key && cosign sign --key=/tmp/cosign.key --output-signature=/tmp/integrationcli-builder_latest.sig --yes ${_IMAGE_NAME}-builder:latest'
- name: 'gcr.io/projectsigstore/cosign:latest'
  id: attach_latest_sign_integrationcli_builder
  entrypoint: 'sh'
  args:
    - '-c'
    - 'cosign attach signature --signature=/tmp/integrationcli-builder_latest.sig ${_IMAGE_NAME}-builder:latest'

#repo name
substitutions:
  _REPO: "images"
  _COSIGN_PASSWORD: "set-externally"
  _COSIGN_PRIVATE_KEY: "set-externally"
  _IMAGE_NAME: "us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/integrationcli"

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  dynamic_substitutions: true
