apiVersion: skaffold/v4beta7
kind: Config
customActions:
- name: render-app-integration
  containers:
  - name: render
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:66e2681aa3099b4e517e4cdcdefff8f2aa45d305007124ccdc09686f6712d018
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        echo "Sample manifest rendered content" > manifest.txt
        gsutil cp manifest.txt $CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt
        echo {\"resultStatus\": \"SUCCEEDED\", \"manifestFile\": \"$CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt\"} > results.json
        gsutil cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
- name: deploy-app-integration
  containers:
  - name: deploy
    #image: us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest
    image: us-docker.pkg.dev/nandanks-151422/images/integrationcli-deploy:debug
    command: ['sh']
    args:
      - '-c'
      - |-
        integrationcli integrations apply --env=dev --reg=$CLOUD_DEPLOY_LOCATION --proj=$CLOUD_DEPLOY_PROJECT --pipeline=$CLOUD_DEPLOY_DELIVERY_PIPELINE --release=$CLOUD_DEPLOY_RELEASE --output-gcs-path=$CLOUD_DEPLOY_OUTPUT_GCS_PATH --metadata-token
